name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npx playwright test
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: 'https://www.rijksmuseum.nl/api'
          CULTURE: 'en'
